version: '2'
services:
  user:
    network_mode: "host"
    restart: "always"
    build: .
    image: user-service
    volumes:
      - /security:/security
    environment:
      TZ: "Europe/Amsterdam"
