version: '2'
services:
  user:
    network_mode: "host"
    restart: "always"
    build: .
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "user"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"