server:
  port: 8443

spring:
  profiles:
    active:
    - prod
  application:
    name: users
  config:
    import: optional:configserver:http://host.docker.internal:5678
  main:
    allow-bean-definition-overriding: true
