server:
  port: 8443

spring:
  profiles:
    active:
    - prod
  application:
    name: users
  config:
    import: optional:configserver:http://91.210.58.91:5678
  main:
    allow-bean-definition-overriding: true
