name: Build Spring Boot App and Deploy Docker Image to Linux

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.MAVEN_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t user-service:latest .

      - name: Save Docker Image to File
        run: docker save user-service:latest | gzip > user-service.tar.gz

      - name: Copy Image to Remote Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "user-service.tar.gz"
          target: "/tmp"

      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load < /tmp/user-service.tar.gz
            docker stop user-service || true
            docker rm user-service || true
            docker run -d --name user-service -p 8443:8443 -v - -v $HOME/user-service/certs:/security user-service:latest
